
stages:
  - pre-build
  - build
  - release


variables:
  DATE_CMD: "date +%Y%m%d"
  GFC_BUILD_IMAGE: "git.pivotalsys.com:5005/infrastructure/gfc-build-docker:1.6"
  SHELLCHECK_IMAGE: "git.pivotalsys.com:5005/containers/docker-shellcheck:1.0"


pre-build:manual-trigger:
  image: alpine:3.5
  stage: pre-build
  script:
    - env
    - exec true
  when: always
  #####################################################
  ### All branches default to manual triggering
  #####################################################
  only:
    - branches
    
  ##################################################################
  # We exclude branches that we want to have automated triggering
  # this
  # - All Tags
  # - develop/* branch
  # - release/* branch
  ##################################################################
  allow_failure: false

## build gfc_release
build:release-binary:
  image: $GFC_BUILD_IMAGE
  stage: build
  script:
    - cd src
    - make
  tags:
    - docker
  when: manual
  allow_failure: true
  only:
    - branches
    - tags
  artifacts:
    untracked: true
    when: on_success
    expire_in: 1 day
    name: "asb_binary-$CI_BUILD_REF_SLUG-${CI_BUILD_REF:0:7}-$($DATE_CMD).tgz"

build:docs:
  image: $GFC_BUILD_IMAGE
  stage: build
  script:
    - cd docs
    - make
  tags:
    - docker
  when: always
  allow_failure: true
  only:
    - branches
    - tags
  artifacts:
    untracked: true
    when: on_success
    expire_in: 1 day
    name: "asb_docs-$CI_BUILD_REF_SLUG-${CI_BUILD_REF:0:7}-$($DATE_CMD).tgz"
    
pages:
    stage: release
    script:
        - cp -r build/doc/html public/
    artifacts:
        paths:
            - public
    when: on_success
    only:
        - tags

